pipeline {

    agent any

    stages {
        stage('Deploy') {
            steps {
                sh 'echo "Deploying...."'
                dir('frontend') {
                    sh 'docker ps -aq --filter "name=frontend" | xargs -r docker rm -f'
                    sh 'docker images -aq frontend | xargs -r docker rmi'
                    sh 'docker build -t frontend .'
                    sh 'docker run -d --name frontend --network cs304 -p 8083:8080 frontend'
                }
            }
        }
    }
}