pipeline {

    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Building...."'
                dir('backend') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Testing...."'
                dir('backend') {
                    sh 'mvn test'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying...."'
                dir('backend') {
                    sh 'mvn package -DskipTests'
                    sh 'docker ps -aq --filter "name=backend" | xargs -r docker rm -f'
                    sh 'docker images -aq backend | xargs -r docker rmi'
                    sh 'docker build -t backend .'
                    sh 'docker run -d --name backend --network cs304 -p 8082:8082 backend'
                }
            }
        }
    }
}